wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.30
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.3
epochs:
  desc: null
  value: 50
read_docs:
  desc: null
  value: 1000
